# Generated by Django 5.1.6 on 2025-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('threat_level', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
