# Generated by Django 5.1.7 on 2025-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackshield', '0002_malwaresignature_scanhistory_remove_report_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='threat_name',
            field=models.CharField(max_length=255),
        ),
    ]
